// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package dma_reg_pkg;

  // Param list
  parameter int NumIntClearSources = 11;
  parameter int NumAadWords = 8;
  parameter int NumAlerts = 2;

  // Address widths within the block
  parameter int BlockAw = 9;

  // Number of registers for every interface
  parameter int NumRegs = 100;

  // Alert indices
  typedef enum int {
    AlertFatalFaultIdx = 0,
    AlertRecovFaultIdx = 1
  } dma_alert_idx_t;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } dma_error;
    struct packed {
      logic        q;
    } dma_chunk_done;
    struct packed {
      logic        q;
    } dma_done;
  } dma_reg2hw_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } dma_error;
    struct packed {
      logic        q;
    } dma_chunk_done;
    struct packed {
      logic        q;
    } dma_done;
  } dma_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } dma_error;
    struct packed {
      logic        q;
      logic        qe;
    } dma_chunk_done;
    struct packed {
      logic        q;
      logic        qe;
    } dma_done;
  } dma_reg2hw_intr_test_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } recov_fault;
    struct packed {
      logic        q;
      logic        qe;
    } fatal_fault;
  } dma_reg2hw_alert_test_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_src_addr_lo_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_src_addr_hi_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_dst_addr_lo_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_dst_addr_hi_reg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  q;
    } dst_asid;
    struct packed {
      logic [3:0]  q;
    } src_asid;
  } dma_reg2hw_addr_space_id_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } dma_reg2hw_enabled_memory_range_base_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } dma_reg2hw_enabled_memory_range_limit_reg_t;

  typedef struct packed {
    logic        q;
  } dma_reg2hw_range_valid_reg_t;

  typedef struct packed {
    logic [3:0]  q;
  } dma_reg2hw_range_regwen_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_total_data_size_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_chunk_data_size_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } dma_reg2hw_transfer_width_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } go;
    struct packed {
      logic        q;
    } abort;
    struct packed {
      logic        q;
    } aes_mode;
    struct packed {
      logic [1:0]  q;
    } aes_op;
    struct packed {
      logic        q;
    } initial_transfer;
    struct packed {
      logic        q;
    } digest_swap;
    struct packed {
      logic        q;
    } hardware_handshake_enable;
    struct packed {
      logic [1:0]  q;
    } digest;
    struct packed {
      logic        q;
    } write_en;
    struct packed {
      logic        q;
    } read_en;
  } dma_reg2hw_control_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } wrap;
    struct packed {
      logic        q;
    } increment;
  } dma_reg2hw_src_config_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } wrap;
    struct packed {
      logic        q;
    } increment;
  } dma_reg2hw_dst_config_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } tag_failed;
    struct packed {
      logic        q;
      logic        qe;
    } tag_valid;
    struct packed {
      logic        q;
    } chunk_done;
    struct packed {
      logic        q;
      logic        qe;
    } sha2_digest_valid;
    struct packed {
      logic        q;
      logic        qe;
    } error;
    struct packed {
      logic        q;
    } done;
    struct packed {
      logic        q;
    } busy;
  } dma_reg2hw_status_reg_t;

  typedef struct packed {
    logic [10:0] q;
  } dma_reg2hw_handshake_intr_enable_reg_t;

  typedef struct packed {
    logic [10:0] q;
  } dma_reg2hw_clear_intr_src_reg_t;

  typedef struct packed {
    logic [10:0] q;
  } dma_reg2hw_clear_intr_bus_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_intr_src_addr_mreg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_intr_src_wr_val_mreg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  q;
    } aad_blocks;
    struct packed {
      logic [2:0]  q;
    } prng_reseed_rate;
    struct packed {
      logic        q;
    } sideload;
    struct packed {
      logic [2:0]  q;
    } key_len;
  } dma_reg2hw_aes_ctrl_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_key_share0_mreg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_key_share1_mreg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_iv_mreg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_aad_mreg_t;

  typedef struct packed {
    logic [31:0] q;
  } dma_reg2hw_tag_in_mreg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } dma_reg2hw_tag_out_mreg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } dma_error;
    struct packed {
      logic        d;
      logic        de;
    } dma_chunk_done;
    struct packed {
      logic        d;
      logic        de;
    } dma_done;
  } dma_hw2reg_intr_state_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_src_addr_lo_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_src_addr_hi_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_dst_addr_lo_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_dst_addr_hi_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } dma_hw2reg_cfg_regwen_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } go;
    struct packed {
      logic        d;
      logic        de;
    } abort;
    struct packed {
      logic        d;
      logic        de;
    } initial_transfer;
  } dma_hw2reg_control_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } tag_failed;
    struct packed {
      logic        d;
      logic        de;
    } tag_valid;
    struct packed {
      logic        d;
      logic        de;
    } chunk_done;
    struct packed {
      logic        d;
      logic        de;
    } sha2_digest_valid;
    struct packed {
      logic        d;
      logic        de;
    } error;
    struct packed {
      logic        d;
      logic        de;
    } aborted;
    struct packed {
      logic        d;
      logic        de;
    } done;
    struct packed {
      logic        d;
      logic        de;
    } busy;
  } dma_hw2reg_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } aes_tag_error;
    struct packed {
      logic        d;
      logic        de;
    } asid_error;
    struct packed {
      logic        d;
      logic        de;
    } range_valid_error;
    struct packed {
      logic        d;
      logic        de;
    } base_limit_error;
    struct packed {
      logic        d;
      logic        de;
    } bus_error;
    struct packed {
      logic        d;
      logic        de;
    } size_error;
    struct packed {
      logic        d;
      logic        de;
    } opcode_error;
    struct packed {
      logic        d;
      logic        de;
    } dst_addr_error;
    struct packed {
      logic        d;
      logic        de;
    } src_addr_error;
  } dma_hw2reg_error_code_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_sha2_digest_mreg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_key_share0_mreg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_key_share1_mreg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_iv_mreg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_aad_mreg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } dma_hw2reg_tag_in_mreg_t;

  typedef struct packed {
    logic [31:0] d;
  } dma_hw2reg_tag_out_mreg_t;

  // Register -> HW type
  typedef struct packed {
    dma_reg2hw_intr_state_reg_t intr_state; // [2220:2218]
    dma_reg2hw_intr_enable_reg_t intr_enable; // [2217:2215]
    dma_reg2hw_intr_test_reg_t intr_test; // [2214:2209]
    dma_reg2hw_alert_test_reg_t alert_test; // [2208:2205]
    dma_reg2hw_src_addr_lo_reg_t src_addr_lo; // [2204:2173]
    dma_reg2hw_src_addr_hi_reg_t src_addr_hi; // [2172:2141]
    dma_reg2hw_dst_addr_lo_reg_t dst_addr_lo; // [2140:2109]
    dma_reg2hw_dst_addr_hi_reg_t dst_addr_hi; // [2108:2077]
    dma_reg2hw_addr_space_id_reg_t addr_space_id; // [2076:2069]
    dma_reg2hw_enabled_memory_range_base_reg_t enabled_memory_range_base; // [2068:2036]
    dma_reg2hw_enabled_memory_range_limit_reg_t enabled_memory_range_limit; // [2035:2003]
    dma_reg2hw_range_valid_reg_t range_valid; // [2002:2002]
    dma_reg2hw_range_regwen_reg_t range_regwen; // [2001:1998]
    dma_reg2hw_total_data_size_reg_t total_data_size; // [1997:1966]
    dma_reg2hw_chunk_data_size_reg_t chunk_data_size; // [1965:1934]
    dma_reg2hw_transfer_width_reg_t transfer_width; // [1933:1932]
    dma_reg2hw_control_reg_t control; // [1931:1919]
    dma_reg2hw_src_config_reg_t src_config; // [1918:1917]
    dma_reg2hw_dst_config_reg_t dst_config; // [1916:1915]
    dma_reg2hw_status_reg_t status; // [1914:1904]
    dma_reg2hw_handshake_intr_enable_reg_t handshake_intr_enable; // [1903:1893]
    dma_reg2hw_clear_intr_src_reg_t clear_intr_src; // [1892:1882]
    dma_reg2hw_clear_intr_bus_reg_t clear_intr_bus; // [1881:1871]
    dma_reg2hw_intr_src_addr_mreg_t [10:0] intr_src_addr; // [1870:1519]
    dma_reg2hw_intr_src_wr_val_mreg_t [10:0] intr_src_wr_val; // [1518:1167]
    dma_reg2hw_aes_ctrl_reg_t aes_ctrl; // [1166:1156]
    dma_reg2hw_key_share0_mreg_t [7:0] key_share0; // [1155:900]
    dma_reg2hw_key_share1_mreg_t [7:0] key_share1; // [899:644]
    dma_reg2hw_iv_mreg_t [3:0] iv; // [643:516]
    dma_reg2hw_aad_mreg_t [7:0] aad; // [515:260]
    dma_reg2hw_tag_in_mreg_t [3:0] tag_in; // [259:132]
    dma_reg2hw_tag_out_mreg_t [3:0] tag_out; // [131:0]
  } dma_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    dma_hw2reg_intr_state_reg_t intr_state; // [1893:1888]
    dma_hw2reg_src_addr_lo_reg_t src_addr_lo; // [1887:1855]
    dma_hw2reg_src_addr_hi_reg_t src_addr_hi; // [1854:1822]
    dma_hw2reg_dst_addr_lo_reg_t dst_addr_lo; // [1821:1789]
    dma_hw2reg_dst_addr_hi_reg_t dst_addr_hi; // [1788:1756]
    dma_hw2reg_cfg_regwen_reg_t cfg_regwen; // [1755:1752]
    dma_hw2reg_control_reg_t control; // [1751:1746]
    dma_hw2reg_status_reg_t status; // [1745:1730]
    dma_hw2reg_error_code_reg_t error_code; // [1729:1712]
    dma_hw2reg_sha2_digest_mreg_t [15:0] sha2_digest; // [1711:1184]
    dma_hw2reg_key_share0_mreg_t [7:0] key_share0; // [1183:920]
    dma_hw2reg_key_share1_mreg_t [7:0] key_share1; // [919:656]
    dma_hw2reg_iv_mreg_t [3:0] iv; // [655:524]
    dma_hw2reg_aad_mreg_t [7:0] aad; // [523:260]
    dma_hw2reg_tag_in_mreg_t [3:0] tag_in; // [259:128]
    dma_hw2reg_tag_out_mreg_t [3:0] tag_out; // [127:0]
  } dma_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] DMA_INTR_STATE_OFFSET = 9'h 0;
  parameter logic [BlockAw-1:0] DMA_INTR_ENABLE_OFFSET = 9'h 4;
  parameter logic [BlockAw-1:0] DMA_INTR_TEST_OFFSET = 9'h 8;
  parameter logic [BlockAw-1:0] DMA_ALERT_TEST_OFFSET = 9'h c;
  parameter logic [BlockAw-1:0] DMA_SRC_ADDR_LO_OFFSET = 9'h 10;
  parameter logic [BlockAw-1:0] DMA_SRC_ADDR_HI_OFFSET = 9'h 14;
  parameter logic [BlockAw-1:0] DMA_DST_ADDR_LO_OFFSET = 9'h 18;
  parameter logic [BlockAw-1:0] DMA_DST_ADDR_HI_OFFSET = 9'h 1c;
  parameter logic [BlockAw-1:0] DMA_ADDR_SPACE_ID_OFFSET = 9'h 20;
  parameter logic [BlockAw-1:0] DMA_ENABLED_MEMORY_RANGE_BASE_OFFSET = 9'h 24;
  parameter logic [BlockAw-1:0] DMA_ENABLED_MEMORY_RANGE_LIMIT_OFFSET = 9'h 28;
  parameter logic [BlockAw-1:0] DMA_RANGE_VALID_OFFSET = 9'h 2c;
  parameter logic [BlockAw-1:0] DMA_RANGE_REGWEN_OFFSET = 9'h 30;
  parameter logic [BlockAw-1:0] DMA_CFG_REGWEN_OFFSET = 9'h 34;
  parameter logic [BlockAw-1:0] DMA_TOTAL_DATA_SIZE_OFFSET = 9'h 38;
  parameter logic [BlockAw-1:0] DMA_CHUNK_DATA_SIZE_OFFSET = 9'h 3c;
  parameter logic [BlockAw-1:0] DMA_TRANSFER_WIDTH_OFFSET = 9'h 40;
  parameter logic [BlockAw-1:0] DMA_CONTROL_OFFSET = 9'h 44;
  parameter logic [BlockAw-1:0] DMA_SRC_CONFIG_OFFSET = 9'h 48;
  parameter logic [BlockAw-1:0] DMA_DST_CONFIG_OFFSET = 9'h 4c;
  parameter logic [BlockAw-1:0] DMA_STATUS_OFFSET = 9'h 50;
  parameter logic [BlockAw-1:0] DMA_ERROR_CODE_OFFSET = 9'h 54;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_0_OFFSET = 9'h 58;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_1_OFFSET = 9'h 5c;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_2_OFFSET = 9'h 60;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_3_OFFSET = 9'h 64;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_4_OFFSET = 9'h 68;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_5_OFFSET = 9'h 6c;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_6_OFFSET = 9'h 70;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_7_OFFSET = 9'h 74;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_8_OFFSET = 9'h 78;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_9_OFFSET = 9'h 7c;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_10_OFFSET = 9'h 80;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_11_OFFSET = 9'h 84;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_12_OFFSET = 9'h 88;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_13_OFFSET = 9'h 8c;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_14_OFFSET = 9'h 90;
  parameter logic [BlockAw-1:0] DMA_SHA2_DIGEST_15_OFFSET = 9'h 94;
  parameter logic [BlockAw-1:0] DMA_HANDSHAKE_INTR_ENABLE_OFFSET = 9'h 98;
  parameter logic [BlockAw-1:0] DMA_CLEAR_INTR_SRC_OFFSET = 9'h 9c;
  parameter logic [BlockAw-1:0] DMA_CLEAR_INTR_BUS_OFFSET = 9'h a0;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_0_OFFSET = 9'h a4;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_1_OFFSET = 9'h a8;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_2_OFFSET = 9'h ac;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_3_OFFSET = 9'h b0;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_4_OFFSET = 9'h b4;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_5_OFFSET = 9'h b8;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_6_OFFSET = 9'h bc;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_7_OFFSET = 9'h c0;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_8_OFFSET = 9'h c4;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_9_OFFSET = 9'h c8;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_ADDR_10_OFFSET = 9'h cc;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_0_OFFSET = 9'h 124;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_1_OFFSET = 9'h 128;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_2_OFFSET = 9'h 12c;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_3_OFFSET = 9'h 130;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_4_OFFSET = 9'h 134;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_5_OFFSET = 9'h 138;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_6_OFFSET = 9'h 13c;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_7_OFFSET = 9'h 140;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_8_OFFSET = 9'h 144;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_9_OFFSET = 9'h 148;
  parameter logic [BlockAw-1:0] DMA_INTR_SRC_WR_VAL_10_OFFSET = 9'h 14c;
  parameter logic [BlockAw-1:0] DMA_AES_CTRL_OFFSET = 9'h 150;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE0_0_OFFSET = 9'h 154;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE0_1_OFFSET = 9'h 158;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE0_2_OFFSET = 9'h 15c;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE0_3_OFFSET = 9'h 160;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE0_4_OFFSET = 9'h 164;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE0_5_OFFSET = 9'h 168;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE0_6_OFFSET = 9'h 16c;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE0_7_OFFSET = 9'h 170;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE1_0_OFFSET = 9'h 174;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE1_1_OFFSET = 9'h 178;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE1_2_OFFSET = 9'h 17c;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE1_3_OFFSET = 9'h 180;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE1_4_OFFSET = 9'h 184;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE1_5_OFFSET = 9'h 188;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE1_6_OFFSET = 9'h 18c;
  parameter logic [BlockAw-1:0] DMA_KEY_SHARE1_7_OFFSET = 9'h 190;
  parameter logic [BlockAw-1:0] DMA_IV_0_OFFSET = 9'h 194;
  parameter logic [BlockAw-1:0] DMA_IV_1_OFFSET = 9'h 198;
  parameter logic [BlockAw-1:0] DMA_IV_2_OFFSET = 9'h 19c;
  parameter logic [BlockAw-1:0] DMA_IV_3_OFFSET = 9'h 1a0;
  parameter logic [BlockAw-1:0] DMA_AAD_0_OFFSET = 9'h 1a4;
  parameter logic [BlockAw-1:0] DMA_AAD_1_OFFSET = 9'h 1a8;
  parameter logic [BlockAw-1:0] DMA_AAD_2_OFFSET = 9'h 1ac;
  parameter logic [BlockAw-1:0] DMA_AAD_3_OFFSET = 9'h 1b0;
  parameter logic [BlockAw-1:0] DMA_AAD_4_OFFSET = 9'h 1b4;
  parameter logic [BlockAw-1:0] DMA_AAD_5_OFFSET = 9'h 1b8;
  parameter logic [BlockAw-1:0] DMA_AAD_6_OFFSET = 9'h 1bc;
  parameter logic [BlockAw-1:0] DMA_AAD_7_OFFSET = 9'h 1c0;
  parameter logic [BlockAw-1:0] DMA_TAG_IN_0_OFFSET = 9'h 1c4;
  parameter logic [BlockAw-1:0] DMA_TAG_IN_1_OFFSET = 9'h 1c8;
  parameter logic [BlockAw-1:0] DMA_TAG_IN_2_OFFSET = 9'h 1cc;
  parameter logic [BlockAw-1:0] DMA_TAG_IN_3_OFFSET = 9'h 1d0;
  parameter logic [BlockAw-1:0] DMA_TAG_OUT_0_OFFSET = 9'h 1d4;
  parameter logic [BlockAw-1:0] DMA_TAG_OUT_1_OFFSET = 9'h 1d8;
  parameter logic [BlockAw-1:0] DMA_TAG_OUT_2_OFFSET = 9'h 1dc;
  parameter logic [BlockAw-1:0] DMA_TAG_OUT_3_OFFSET = 9'h 1e0;

  // Reset values for hwext registers and their fields
  parameter logic [2:0] DMA_INTR_TEST_RESVAL = 3'h 0;
  parameter logic [0:0] DMA_INTR_TEST_DMA_DONE_RESVAL = 1'h 0;
  parameter logic [0:0] DMA_INTR_TEST_DMA_CHUNK_DONE_RESVAL = 1'h 0;
  parameter logic [0:0] DMA_INTR_TEST_DMA_ERROR_RESVAL = 1'h 0;
  parameter logic [1:0] DMA_ALERT_TEST_RESVAL = 2'h 0;
  parameter logic [0:0] DMA_ALERT_TEST_FATAL_FAULT_RESVAL = 1'h 0;
  parameter logic [0:0] DMA_ALERT_TEST_RECOV_FAULT_RESVAL = 1'h 0;
  parameter logic [3:0] DMA_CFG_REGWEN_RESVAL = 4'h 6;
  parameter logic [3:0] DMA_CFG_REGWEN_REGWEN_RESVAL = 4'h 6;
  parameter logic [31:0] DMA_TAG_OUT_0_RESVAL = 32'h 0;
  parameter logic [31:0] DMA_TAG_OUT_0_TAG_0_RESVAL = 32'h 0;
  parameter logic [31:0] DMA_TAG_OUT_1_RESVAL = 32'h 0;
  parameter logic [31:0] DMA_TAG_OUT_1_TAG_1_RESVAL = 32'h 0;
  parameter logic [31:0] DMA_TAG_OUT_2_RESVAL = 32'h 0;
  parameter logic [31:0] DMA_TAG_OUT_2_TAG_2_RESVAL = 32'h 0;
  parameter logic [31:0] DMA_TAG_OUT_3_RESVAL = 32'h 0;
  parameter logic [31:0] DMA_TAG_OUT_3_TAG_3_RESVAL = 32'h 0;

  // Register index
  typedef enum int {
    DMA_INTR_STATE,
    DMA_INTR_ENABLE,
    DMA_INTR_TEST,
    DMA_ALERT_TEST,
    DMA_SRC_ADDR_LO,
    DMA_SRC_ADDR_HI,
    DMA_DST_ADDR_LO,
    DMA_DST_ADDR_HI,
    DMA_ADDR_SPACE_ID,
    DMA_ENABLED_MEMORY_RANGE_BASE,
    DMA_ENABLED_MEMORY_RANGE_LIMIT,
    DMA_RANGE_VALID,
    DMA_RANGE_REGWEN,
    DMA_CFG_REGWEN,
    DMA_TOTAL_DATA_SIZE,
    DMA_CHUNK_DATA_SIZE,
    DMA_TRANSFER_WIDTH,
    DMA_CONTROL,
    DMA_SRC_CONFIG,
    DMA_DST_CONFIG,
    DMA_STATUS,
    DMA_ERROR_CODE,
    DMA_SHA2_DIGEST_0,
    DMA_SHA2_DIGEST_1,
    DMA_SHA2_DIGEST_2,
    DMA_SHA2_DIGEST_3,
    DMA_SHA2_DIGEST_4,
    DMA_SHA2_DIGEST_5,
    DMA_SHA2_DIGEST_6,
    DMA_SHA2_DIGEST_7,
    DMA_SHA2_DIGEST_8,
    DMA_SHA2_DIGEST_9,
    DMA_SHA2_DIGEST_10,
    DMA_SHA2_DIGEST_11,
    DMA_SHA2_DIGEST_12,
    DMA_SHA2_DIGEST_13,
    DMA_SHA2_DIGEST_14,
    DMA_SHA2_DIGEST_15,
    DMA_HANDSHAKE_INTR_ENABLE,
    DMA_CLEAR_INTR_SRC,
    DMA_CLEAR_INTR_BUS,
    DMA_INTR_SRC_ADDR_0,
    DMA_INTR_SRC_ADDR_1,
    DMA_INTR_SRC_ADDR_2,
    DMA_INTR_SRC_ADDR_3,
    DMA_INTR_SRC_ADDR_4,
    DMA_INTR_SRC_ADDR_5,
    DMA_INTR_SRC_ADDR_6,
    DMA_INTR_SRC_ADDR_7,
    DMA_INTR_SRC_ADDR_8,
    DMA_INTR_SRC_ADDR_9,
    DMA_INTR_SRC_ADDR_10,
    DMA_INTR_SRC_WR_VAL_0,
    DMA_INTR_SRC_WR_VAL_1,
    DMA_INTR_SRC_WR_VAL_2,
    DMA_INTR_SRC_WR_VAL_3,
    DMA_INTR_SRC_WR_VAL_4,
    DMA_INTR_SRC_WR_VAL_5,
    DMA_INTR_SRC_WR_VAL_6,
    DMA_INTR_SRC_WR_VAL_7,
    DMA_INTR_SRC_WR_VAL_8,
    DMA_INTR_SRC_WR_VAL_9,
    DMA_INTR_SRC_WR_VAL_10,
    DMA_AES_CTRL,
    DMA_KEY_SHARE0_0,
    DMA_KEY_SHARE0_1,
    DMA_KEY_SHARE0_2,
    DMA_KEY_SHARE0_3,
    DMA_KEY_SHARE0_4,
    DMA_KEY_SHARE0_5,
    DMA_KEY_SHARE0_6,
    DMA_KEY_SHARE0_7,
    DMA_KEY_SHARE1_0,
    DMA_KEY_SHARE1_1,
    DMA_KEY_SHARE1_2,
    DMA_KEY_SHARE1_3,
    DMA_KEY_SHARE1_4,
    DMA_KEY_SHARE1_5,
    DMA_KEY_SHARE1_6,
    DMA_KEY_SHARE1_7,
    DMA_IV_0,
    DMA_IV_1,
    DMA_IV_2,
    DMA_IV_3,
    DMA_AAD_0,
    DMA_AAD_1,
    DMA_AAD_2,
    DMA_AAD_3,
    DMA_AAD_4,
    DMA_AAD_5,
    DMA_AAD_6,
    DMA_AAD_7,
    DMA_TAG_IN_0,
    DMA_TAG_IN_1,
    DMA_TAG_IN_2,
    DMA_TAG_IN_3,
    DMA_TAG_OUT_0,
    DMA_TAG_OUT_1,
    DMA_TAG_OUT_2,
    DMA_TAG_OUT_3
  } dma_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] DMA_PERMIT [100] = '{
    4'b 0001, // index[ 0] DMA_INTR_STATE
    4'b 0001, // index[ 1] DMA_INTR_ENABLE
    4'b 0001, // index[ 2] DMA_INTR_TEST
    4'b 0001, // index[ 3] DMA_ALERT_TEST
    4'b 1111, // index[ 4] DMA_SRC_ADDR_LO
    4'b 1111, // index[ 5] DMA_SRC_ADDR_HI
    4'b 1111, // index[ 6] DMA_DST_ADDR_LO
    4'b 1111, // index[ 7] DMA_DST_ADDR_HI
    4'b 0001, // index[ 8] DMA_ADDR_SPACE_ID
    4'b 1111, // index[ 9] DMA_ENABLED_MEMORY_RANGE_BASE
    4'b 1111, // index[10] DMA_ENABLED_MEMORY_RANGE_LIMIT
    4'b 0001, // index[11] DMA_RANGE_VALID
    4'b 0001, // index[12] DMA_RANGE_REGWEN
    4'b 0001, // index[13] DMA_CFG_REGWEN
    4'b 1111, // index[14] DMA_TOTAL_DATA_SIZE
    4'b 1111, // index[15] DMA_CHUNK_DATA_SIZE
    4'b 0001, // index[16] DMA_TRANSFER_WIDTH
    4'b 1111, // index[17] DMA_CONTROL
    4'b 0001, // index[18] DMA_SRC_CONFIG
    4'b 0001, // index[19] DMA_DST_CONFIG
    4'b 0001, // index[20] DMA_STATUS
    4'b 0011, // index[21] DMA_ERROR_CODE
    4'b 1111, // index[22] DMA_SHA2_DIGEST_0
    4'b 1111, // index[23] DMA_SHA2_DIGEST_1
    4'b 1111, // index[24] DMA_SHA2_DIGEST_2
    4'b 1111, // index[25] DMA_SHA2_DIGEST_3
    4'b 1111, // index[26] DMA_SHA2_DIGEST_4
    4'b 1111, // index[27] DMA_SHA2_DIGEST_5
    4'b 1111, // index[28] DMA_SHA2_DIGEST_6
    4'b 1111, // index[29] DMA_SHA2_DIGEST_7
    4'b 1111, // index[30] DMA_SHA2_DIGEST_8
    4'b 1111, // index[31] DMA_SHA2_DIGEST_9
    4'b 1111, // index[32] DMA_SHA2_DIGEST_10
    4'b 1111, // index[33] DMA_SHA2_DIGEST_11
    4'b 1111, // index[34] DMA_SHA2_DIGEST_12
    4'b 1111, // index[35] DMA_SHA2_DIGEST_13
    4'b 1111, // index[36] DMA_SHA2_DIGEST_14
    4'b 1111, // index[37] DMA_SHA2_DIGEST_15
    4'b 0011, // index[38] DMA_HANDSHAKE_INTR_ENABLE
    4'b 0011, // index[39] DMA_CLEAR_INTR_SRC
    4'b 0011, // index[40] DMA_CLEAR_INTR_BUS
    4'b 1111, // index[41] DMA_INTR_SRC_ADDR_0
    4'b 1111, // index[42] DMA_INTR_SRC_ADDR_1
    4'b 1111, // index[43] DMA_INTR_SRC_ADDR_2
    4'b 1111, // index[44] DMA_INTR_SRC_ADDR_3
    4'b 1111, // index[45] DMA_INTR_SRC_ADDR_4
    4'b 1111, // index[46] DMA_INTR_SRC_ADDR_5
    4'b 1111, // index[47] DMA_INTR_SRC_ADDR_6
    4'b 1111, // index[48] DMA_INTR_SRC_ADDR_7
    4'b 1111, // index[49] DMA_INTR_SRC_ADDR_8
    4'b 1111, // index[50] DMA_INTR_SRC_ADDR_9
    4'b 1111, // index[51] DMA_INTR_SRC_ADDR_10
    4'b 1111, // index[52] DMA_INTR_SRC_WR_VAL_0
    4'b 1111, // index[53] DMA_INTR_SRC_WR_VAL_1
    4'b 1111, // index[54] DMA_INTR_SRC_WR_VAL_2
    4'b 1111, // index[55] DMA_INTR_SRC_WR_VAL_3
    4'b 1111, // index[56] DMA_INTR_SRC_WR_VAL_4
    4'b 1111, // index[57] DMA_INTR_SRC_WR_VAL_5
    4'b 1111, // index[58] DMA_INTR_SRC_WR_VAL_6
    4'b 1111, // index[59] DMA_INTR_SRC_WR_VAL_7
    4'b 1111, // index[60] DMA_INTR_SRC_WR_VAL_8
    4'b 1111, // index[61] DMA_INTR_SRC_WR_VAL_9
    4'b 1111, // index[62] DMA_INTR_SRC_WR_VAL_10
    4'b 0011, // index[63] DMA_AES_CTRL
    4'b 1111, // index[64] DMA_KEY_SHARE0_0
    4'b 1111, // index[65] DMA_KEY_SHARE0_1
    4'b 1111, // index[66] DMA_KEY_SHARE0_2
    4'b 1111, // index[67] DMA_KEY_SHARE0_3
    4'b 1111, // index[68] DMA_KEY_SHARE0_4
    4'b 1111, // index[69] DMA_KEY_SHARE0_5
    4'b 1111, // index[70] DMA_KEY_SHARE0_6
    4'b 1111, // index[71] DMA_KEY_SHARE0_7
    4'b 1111, // index[72] DMA_KEY_SHARE1_0
    4'b 1111, // index[73] DMA_KEY_SHARE1_1
    4'b 1111, // index[74] DMA_KEY_SHARE1_2
    4'b 1111, // index[75] DMA_KEY_SHARE1_3
    4'b 1111, // index[76] DMA_KEY_SHARE1_4
    4'b 1111, // index[77] DMA_KEY_SHARE1_5
    4'b 1111, // index[78] DMA_KEY_SHARE1_6
    4'b 1111, // index[79] DMA_KEY_SHARE1_7
    4'b 1111, // index[80] DMA_IV_0
    4'b 1111, // index[81] DMA_IV_1
    4'b 1111, // index[82] DMA_IV_2
    4'b 1111, // index[83] DMA_IV_3
    4'b 1111, // index[84] DMA_AAD_0
    4'b 1111, // index[85] DMA_AAD_1
    4'b 1111, // index[86] DMA_AAD_2
    4'b 1111, // index[87] DMA_AAD_3
    4'b 1111, // index[88] DMA_AAD_4
    4'b 1111, // index[89] DMA_AAD_5
    4'b 1111, // index[90] DMA_AAD_6
    4'b 1111, // index[91] DMA_AAD_7
    4'b 1111, // index[92] DMA_TAG_IN_0
    4'b 1111, // index[93] DMA_TAG_IN_1
    4'b 1111, // index[94] DMA_TAG_IN_2
    4'b 1111, // index[95] DMA_TAG_IN_3
    4'b 1111, // index[96] DMA_TAG_OUT_0
    4'b 1111, // index[97] DMA_TAG_OUT_1
    4'b 1111, // index[98] DMA_TAG_OUT_2
    4'b 1111  // index[99] DMA_TAG_OUT_3
  };

endpackage
